name: Test ReactJS web app
on: push
jobs:
  Test_Env:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch github repo
        uses: actions/checkout@v3
      - name: Install NodeJS for React
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
      - name: Test React app
        run : npm test
  Deploy:
    needs: Test_Env
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch github repo
        uses: actions/checkout@v3
      - name: Install NodeJS for React
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Deploy to Server
        run: echo "Deploying ..."