name: Test ReactJS web app
#on: [push, workflow_dispatch] #Multiple Triggers
on: 
  pull_request: #Use Types to specify which action of pull_request u want
    types: 
      - opened
      - edited
      - reopened
  push:
    branches:
      - main
      - 'dev-*' # could be: dev-new, dev-new-branch, etc..
      - 'feature/**'  # could be: feature/new, feature/new/branch, etc..
    paths:
      - '.github/workflows/*' # Workflow will not run until u change files in this path
    # paths-ignore:
    # - '.github/workflows/*' # Workflow will not run if u change files in this path
    
jobs:
  Test_Env:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch github repo
        uses: actions/checkout@v3
      - name: Install NodeJS for React
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
      - name: Test React app
        run : npm test
  Build:
    needs: Test_Env
    runs-on: ubuntu-22.04
    outputs:
      script-file: ${{ steps.publish.outputs.file-name }}
    steps:
      - name: Fetch github repo
        uses: actions/checkout@v3
      - name: Install NodeJS for React
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Store value in Outputs  # Publish the filename of .JS in the Artifact
        id: publish   # Use this ID to access the Output to the filename
        run: find /dist/assets/*.js -type f -execdir echo 'file-name={}' >> $GITHUB_OUTPUT ';'  # Shell command to find the filename and store it in the "Output" of Github.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          # dist
          # package.json
  Deploy:
    needs: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: List all files
        run: ls
      - name: Deploy to Server
        run: echo "Deploying ..."